//q
// Generated by Qodo Gen

import net.runelite.client.config.ConfigClient;

import org.junit.Test;
import static org.junit.Assert.*;

public class PatchTest {


    // Successfully patches configuration when server responds with 200
    @Test
    public void test_patch_successful_response() throws Exception {
        OkHttpClient mockClient = Mockito.mock(OkHttpClient.class);
        HttpUrl mockUrl = Mockito.mock(HttpUrl.class);
        Gson mockGson = Mockito.mock(Gson.class);
        ConfigClient configClient = new ConfigClient(mockClient, mockUrl, mockGson);
    
        ConfigPatch patch = new ConfigPatch();
        long profile = 123L;
    
        Response mockResponse = Mockito.mock(Response.class);
        Mockito.when(mockResponse.code()).thenReturn(200);
        Mockito.when(mockResponse.body()).thenReturn(Mockito.mock(ResponseBody.class));
    
        Call mockCall = Mockito.mock(Call.class);
        Mockito.when(mockClient.newCall(Mockito.any(Request.class))).thenReturn(mockCall);
    
        CompletableFuture<ConfigPatchResult> future = configClient.patch(patch, profile);
    
        ArgumentCaptor<Callback> callbackCaptor = ArgumentCaptor.forClass(Callback.class);
        Mockito.verify(mockCall).enqueue(callbackCaptor.capture());
    
        callbackCaptor.getValue().onResponse(mockCall, mockResponse);
    
        Assertions.assertNotNull(future.get());
    }

    // Handles non-200 HTTP responses gracefully
    @Test
    public void test_patch_non_200_response() throws Exception {
        OkHttpClient mockClient = Mockito.mock(OkHttpClient.class);
        HttpUrl mockUrl = Mockito.mock(HttpUrl.class);
        Gson mockGson = Mockito.mock(Gson.class);
        ConfigClient configClient = new ConfigClient(mockClient, mockUrl, mockGson);
    
        ConfigPatch patch = new ConfigPatch();
        long profile = 123L;
    
        Response mockResponse = Mockito.mock(Response.class);
        Mockito.when(mockResponse.code()).thenReturn(404);
        ResponseBody responseBody = Mockito.mock(ResponseBody.class);
        Mockito.when(responseBody.string()).thenReturn("Not Found");
        Mockito.when(mockResponse.body()).thenReturn(responseBody);
    
        Call mockCall = Mockito.mock(Call.class);
        Mockito.when(mockClient.newCall(Mockito.any(Request.class))).thenReturn(mockCall);
    
        CompletableFuture<ConfigPatchResult> future = configClient.patch(patch, profile);
    
        ArgumentCaptor<Callback> callbackCaptor = ArgumentCaptor.forClass(Callback.class);
        Mockito.verify(mockCall).enqueue(callbackCaptor.capture());
    
        callbackCaptor.getValue().onResponse(mockCall, mockResponse);
    
        Assertions.assertNull(future.get());
    }
}